executor: slurm
slurm-status-command: squeue
slurm-status-attempts: 5
jobs: 10
printshellcmds: true
rerun-incomplete: true
show-failed-logs: true
drop-metadata: true
keep-going: false
latency-wait: 120
default-resources:
  - slurm_account=barton
  - slurm_partition=barton
  - mem_mb=8000
  - runtime=60
